import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner"
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "따갈로그를 배워요",
  description: "Generated by GoodNews",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
      <SessionProvider>
        <TRPCReactProvider>
          {children}
          <Toaster />
        </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
